# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

plugin 'cocoapods-art', :sources => [
  'riskident-ios'
]

target 'DeviceIdentDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ClientSecurityKit', '1.6.2'
  # Pods for DeviceIdentDemo

  target 'DeviceIdentDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DeviceIdentDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
